project_id = "krajdsugcvwytpsqnbzs"

[functions.generate-presigned-url]
verify_jwt = false

[functions.upload-to-r2]
verify_jwt = true

[functions.detect-token-holdings]
verify_jwt = false

[functions.paymaster]
verify_jwt = false
