project_id = "krajdsugcvwytpsqnbzs"

[functions.generate-presigned-url]
verify_jwt = false

[functions.upload-to-r2]
verify_jwt = true

[functions.detect-token-holdings]
verify_jwt = false

[functions.paymaster]
verify_jwt = false

[functions.realtime-video]
verify_jwt = false

[functions.agora-token]
verify_jwt = false

[functions.claim-camly]
verify_jwt = true

[functions.treasury-monitor]
verify_jwt = false

[functions.media-create-upload-url]
verify_jwt = true

[functions.media-pin-to-ipfs]
verify_jwt = false

[functions.media-unpin-ipfs]
verify_jwt = true

[functions.media-pin-scheduler]
verify_jwt = false

[functions.media-confirm-upload]
verify_jwt = true
